-- 001_init_tables.sql
-- -------------------

create table if not exists public.users (
  id uuid not null,
  created_at timestamp with time zone not null default now(),
  email text not null,
  display_name text not null,
  partner_id uuid references public.users(id),
  constraint users_pkey primary key (id),
  constraint users_display_name_key unique (display_name),
  constraint users_email_key unique (email)
) TABLESPACE pg_default;

create table if not exists public.transactions (
  id uuid generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  date date not null,
  merchant text not null,
  merchant_normalized text not null,
  description text null,
  amount numeric not null,
  self_amount numeric not null,
  partner_amount numeric not null,
  updated_at timestamp without time zone not null default now(),
  exclude_from_report boolean not null default false,
  type text not null,
  category text not null,
  user_id uuid not null references public.users(id),
  partner_id uuid null references public.users(id), -- optional
  constraint transactions_pkey primary key (id)
) TABLESPACE pg_default;

